version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: monthly
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"