// Code generated by generate_access.go; DO NOT EDIT.
package lotup

//go:generate go run internal/generate/access/generate_access.go

func First[T any](first T, _ any) T {
	return first
}

func Second[T any](_ any, second T) T {
	return second
}

func First3[T any](first T, _, _ any) T {
	return first
}

func Last3[T any](_, _ any, last T) T {
	return last
}

func First4[T any](first T, _, _, _ any) T {
	return first
}

func Last4[T any](_, _, _ any, last T) T {
	return last
}

func First5[T any](first T, _, _, _, _ any) T {
	return first
}

func Last5[T any](_, _, _, _ any, last T) T {
	return last
}

func First6[T any](first T, _, _, _, _, _ any) T {
	return first
}

func Last6[T any](_, _, _, _, _ any, last T) T {
	return last
}

func First7[T any](first T, _, _, _, _, _, _ any) T {
	return first
}

func Last7[T any](_, _, _, _, _, _ any, last T) T {
	return last
}

func First8[T any](first T, _, _, _, _, _, _, _ any) T {
	return first
}

func Last8[T any](_, _, _, _, _, _, _ any, last T) T {
	return last
}

func First9[T any](first T, _, _, _, _, _, _, _, _ any) T {
	return first
}

func Last9[T any](_, _, _, _, _, _, _, _ any, last T) T {
	return last
}
