//go:build generate_monad

package main

import (
	_ "embed"

	"bytes"
	"fmt"
	"io/fs"
	"log/slog"
	"os"
	"os/exec"
	"strings"
	"text/template"
)

const (
	monadGeneratorPath = "internal/generate/access/generate_access.go"
	filename           = "access.go"

	ownerWritePermission = 0o644

	argumentsLimit = 9
)

var (
	//go:embed access.gotmpl
	ofRaw string
)

type Variant struct {
	N int
}

func main() {
	funcMap := template.FuncMap{
		"add": func(x, y int) int { return x + y },
		"sub": func(x, y int) int { return x - y },
	}
	ofTmpl := template.Must(template.New("of").Funcs(funcMap).Parse(ofRaw))

	pkg := detectPackageName()

	var buf bytes.Buffer

	buf.WriteString("// Code generated by generate_access.go; DO NOT EDIT.\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkg))
	buf.WriteString(fmt.Sprintf("//go:generate go run %s\n", monadGeneratorPath))
	buf.WriteString(`
func First[T any](first T, _ any) T {
	return first
}

func Second[T any](_ any, second T) T {
	return second
}
`)

	for n := 3; n <= argumentsLimit; n++ {
		err := ofTmpl.Execute(&buf, Variant{N: n})
		if err != nil {
			panic(err)
		}
	}

	err := os.WriteFile(filename, buf.Bytes(), fs.FileMode(ownerWritePermission))
	if err != nil {
		panic(err)
	}

	slog.Info("done")
}

func detectPackageName() string {
	out, err := exec.Command("go", "list", "-f", "{{.Name}}").Output()
	if err != nil {
		panic(err)
	}

	return strings.TrimSpace(string(out))
}
