import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Enhanced sidebar with better organization and features from 3.8+
  docSidebar: [
    'about',
    'getting-started',
    {
      type: 'category',
      label: '🧢 Core',
      collapsible: false,
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'core'},
      ],
    },
    {
      type: 'category',
      label: '🔄 Iterator',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'iter'},
      ],
    },
    {
      type: 'category',
      label: '👣 Mutable',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'mutable'},
      ],
    },
    {
      type: 'category',
      label: '🏎️ Parallel',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'parallel'},
      ],
    },
    'glossary',
    'contributing',
  ],
};

export default sidebars;
