name: Documentation

on:
  pull_request:
    paths:
      - 'docs/**'
  push:
    paths:
      - 'docs/**'

jobs:
  build-doc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7

      - name: Install dependencies
        run: npm i

      - name: Build Docusaurus project
        run: npm run build

  validate-doc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7

      - name: Install dependencies
        run: npm i

      - name: Run docs helpers checks
        run: npm run check-docs