name: Lint

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  analyze:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          args: --timeout 120s --max-same-issues 50

      # - name: Install mdsf
      #   uses: hougesen/mdsf@main
      # - name: Run mdsf
      #   run: mdsf --debug --log-level warn docs/
